// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotParkApi.Models;

namespace SpotParkApi.Migrations
{
    [DbContext(typeof(SpotParkApiContext))]
    [Migration("20180726171924_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpotParkApi.Models.ParkingSpot", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Availability");

                    b.Property<double>("Cost");

                    b.Property<string>("Email");

                    b.Property<string>("Location");

                    b.Property<string>("LocationIdentifier");

                    b.Property<int>("Size");

                    b.Property<string>("SpecialInstructions");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("ParkingSpot");
                });
#pragma warning restore 612, 618
        }
    }
}
