// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotParkApi.Models;

namespace SpotParkApi.Migrations
{
    [DbContext(typeof(SpotParkApiContext))]
    [Migration("20180727154816_u6")]
    partial class u6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpotParkApi.Models.ParkingSpot", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AvailabilityEnd");

                    b.Property<DateTime>("AvailabilityStart");

                    b.Property<double>("Cost");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("LocationIdentifier")
                        .HasMaxLength(25);

                    b.Property<int>("ReportCount");

                    b.Property<double>("Size");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("ParkingSpot");
                });

            modelBuilder.Entity("SpotParkApi.Models.Report", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Message")
                        .HasMaxLength(200);

                    b.Property<long?>("ParkingSpotID");

                    b.HasKey("ID");

                    b.HasIndex("ParkingSpotID");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("SpotParkApi.Models.Report", b =>
                {
                    b.HasOne("SpotParkApi.Models.ParkingSpot", "ParkingSpot")
                        .WithMany("Reports")
                        .HasForeignKey("ParkingSpotID");
                });
#pragma warning restore 612, 618
        }
    }
}
